### ISSUE TITLE
PSOL 50 - Partido Socialismo e Liberdade 

### ISSUE THREAD

**Issue by marciomr** [marciomr/13M#42]
ID: 131269027034740

**Comment by andrechalom** [comment]
Rodando :)

**Comment by marciomr** [comment]
Valeu

**Comment by andrechalom** [comment]
Feito com a versão do Pull Request, ou seja, ainda precisa ser testada:

PSOL 50 - Partido Socialismo e Liberdade
Curtidas no último mês: 34537
---Número de usuários que confirmaram presença nos eventos: 0---

EDIT: não está funcionando =/

**Comment by marciomr** [comment]
Não está funcionando, mas não consigo entender. Na base de dados está tudo ok.
