### ISSUE TITLE
Mídia

### ISSUE THREAD

**Issue by marciomr** [marciomr/13M#56]
Processar todos as páginas da categoria mídia.

**Comment by marciomr** [comment]
Página NINJA
Interagiram no período: 138051; likes: 410215; média: 2.97 likes por usuário
Confirmados nos eventos: 666

**Comment by marciomr** [comment]
Vou precisar de ajuda com esse. É muito grande e a conexão minha com o FB não está ajudando.

**Comment by andrechalom** [comment]
Página Pragmatismo Político
Interagiram no período: 219506; likes: 710698; média: 3.24 likes por usuário
Confirmados nos eventos: 1311

**Comment by andrechalom** [comment]
Página Jornal GGN
Interagiram no período: 7781; likes: 58484; média: 7.52 likes por usuário
Confirmados nos eventos: 29
Página Carta Maior
Interagiram no período: 67036; likes: 227136; média: 3.39 likes por usuário
Confirmados nos eventos: 651

**Comment by andrechalom** [comment]
Página Brasil 247
Interagiram no período: 83240; likes: 949528; média: 11.41 likes por usuário
Confirmados nos eventos: 928

**Comment by andrechalom** [comment]
Página Revista Caros Amigos
Interagiram no período: 35043; likes: 85072; média: 2.43 likes por usuário
Confirmados nos eventos: 156
Página Rede Brasil Atual
Interagiram no período: 7428; likes: 36836; média: 4.96 likes por usuário
Confirmados nos eventos: 40
Página Tijolaço
Interagiram no período: 8690; likes: 49556; média: 5.7 likes por usuário
Confirmados nos eventos: 12

**Comment by marciomr** [comment]
EL PAÍS Brasil 
     Interagiram no período: 136127
     Likes: 428043
     Média: 3.14 likes por usuário
     Confirmados nos eventos: 2860
Revista Fórum 
     Interagiram no período: 132137
     Likes: 595255
     Média: 4.5 likes por usuário
     Confirmados nos eventos: 920
Diário do Centro do Mundo 
     Interagiram no período: 41285
     Likes: 210286
     Média: 5.09 likes por usuário
     Confirmados nos eventos: 203
CartaCapital 
     Interagiram no período: 180270
     Likes: 457740
     Média: 2.54 likes por usuário
     Confirmados nos eventos: 1447
Época 
     Interagiram no período: 212199
     Likes: 726757
     Média: 3.42 likes por usuário
     Confirmados nos eventos: 17942
Estadão 
     Interagiram no período: 572650
     Likes: 1872811
     Média: 3.27 likes por usuário
     Confirmados nos eventos: 38141
Folha de S.Paulo 
     Interagiram no período: 636447
     Likes: 1851488
     Média: 2.91 likes por usuário
     Confirmados nos eventos: 31340

**Comment by andrechalom** [comment]
Página VEJA
Interagiram no período: 746728; likes: 3589691; média: 4.81 likes por usuário
Confirmados nos eventos: 56504
Página Pragmatismo Político
Interagiram no período: 283971; likes: 1128773; média: 3.97 likes por usuário
Confirmados nos eventos: 2042
Página EBC na Rede
Interagiram no período: 7501; likes: 17601; média: 2.35 likes por usuário
Confirmados nos eventos: 74
Página Rede Record
Interagiram no período: 588801; likes: 2013898; média: 3.42 likes por usuário
Confirmados nos eventos: 2108

**Comment by andrechalom** [comment]
Página G1 - O Portal de Notícias da Globo
Interagiram no período: 1213465; likes: 4486676; média: 3.7 likes por usuário
Confirmados nos eventos: 27643

UOL tb travou por excesso de dados. Vou tentar pelo BD depois

**Comment by marciomr** [comment]
VICE Brasil 
     Interagiram no período: 27612
     Likes: 51928
     Média: 1.88 likes por usuário
     Confirmados nos eventos: 274
Le Monde Diplomatique Brasil 
     Interagiram no período: 3074
     Likes: 5484
     Média: 1.78 likes por usuário
     Confirmados nos eventos: 11
revista piauí 
     Interagiram no período: 29620
     Likes: 52937
     Média: 1.79 likes por usuário
     Confirmados nos eventos: 1085

**Comment by marciomr** [comment]
Portal R7 
     Interagiram no período: 1266213
     Likes: 4824696
     Média: 3.81 likes por usuário
     Confirmados nos eventos: 9702

**Comment by andrechalom** [comment]
Página G1 - O Portal de Notícias da Globo
Interagiram no período: 1213465; likes: 4486676; média: 3.7 likes por usuário
Confirmados nos eventos: 27643

**Comment by andrechalom** [comment]
UOL: 6530946 likes; 924590 usuários; 11041 confirmados (pelo banco de dados)

Página BBC Brasil
Interagiram no período: 311286; likes: 854730; média: 2.75 likes por usuário
Confirmados nos eventos: 10100
Página GloboNews
Interagiram no período: 106543; likes: 344896; média: 3.24 likes por usuário
Confirmados nos eventos: 7496
Página Revista ISTOÉ
Interagiram no período: 281346; likes: 1625341; média: 5.78 likes por usuário
Confirmados nos eventos: 28028

**Comment by allophilia** [comment]
Página Jornal Nacional
Interagiram no período: 441870; likes: 1298728; média: 2.94 likes por usuário
Confirmados nos eventos: 7625
