### ISSUE TITLE
Políticos

### ISSUE THREAD

**Issue by marciomr** [marciomr/13M#57]
Processar todos os dados da categoria políticos.

**Comment by marciomr** [comment]
Página Ricardo Young
Interagiram no período: 11089; likes: 14951; média: 1.35 likes por usuário
Confirmados nos eventos: 1112

**Comment by marciomr** [comment]
Página Fernando Gabeira
Interagiram no período: 17853; likes: 29191; média: 1.64 likes por usuário
Confirmados nos eventos: 3584
Página Cristovam Buarque
Interagiram no período: 20849; likes: 31471; média: 1.51 likes por usuário
Confirmados nos eventos: 1957
Página Romário Faria
Interagiram no período: 329327; likes: 455572; média: 1.38 likes por usuário
Confirmados nos eventos: 5994
Página José Serra
Interagiram no período: 8382; likes: 15695; média: 1.87 likes por usuário
Confirmados nos eventos: 1820
Página Geraldo Alckmin
Interagiram no período: 29224; likes: 95252; média: 3.26 likes por usuário
Confirmados nos eventos: 2765
Página Eduardo Suplicy
Interagiram no período: 87534; likes: 187352; média: 2.14 likes por usuário
Confirmados nos eventos: 354
Página Silas Malafaia
Interagiram no período: 170333; likes: 489480; média: 2.87 likes por usuário
Confirmados nos eventos: 2475
Página Coronel Telhada
Interagiram no período: 223576; likes: 893901; média: 4.0 likes por usuário
Confirmados nos eventos: 8630
Página Dilma Rousseff
Interagiram no período: 213467; likes: 481824; média: 2.26 likes por usuário
Confirmados nos eventos: 476
Página Lula
Interagiram no período: 273357; likes: 878506; média: 3.21 likes por usuário
Confirmados nos eventos: 689
Página Jair Messias Bolsonaro
Interagiram no período: 680995; likes: 2034075; média: 2.99 likes por usuário
Confirmados nos eventos: 37362
Página Aécio Neves
Interagiram no período: 341368; likes: 806343; média: 2.36 likes por usuário
Confirmados nos eventos: 29095
Página Eduardo Cunha
Interagiram no período: 13324; likes: 33620; média: 2.52 likes por usuário
Confirmados nos eventos: 1771
Página Marina Silva
Interagiram no período: 39976; likes: 64589; média: 1.62 likes por usuário
Confirmados nos eventos: 2076
Página Luciana Genro
Interagiram no período: 43851; likes: 73553; média: 1.68 likes por usuário
Confirmados nos eventos: 140
Página Jean Wyllys
Interagiram no período: 200129; likes: 372508; média: 1.86 likes por usuário
Confirmados nos eventos: 857
Página Marcelo Freixo
Interagiram no período: 90107; likes: 160472; média: 1.78 likes por usuário
Confirmados nos eventos: 598

**Comment by andrechalom** [comment]
Página Marco Feliciano
Interagiram no período: 756648; likes: 2404101; média: 3.18 likes por usuário
Confirmados nos eventos: 7342
Página Fernando Haddad
Interagiram no período: 24403; likes: 33772; média: 1.38 likes por usuário
Confirmados nos eventos: 122
Página Ronaldo Caiado
Interagiram no período: 333384; likes: 1442710; média: 4.33 likes por usuário
Confirmados nos eventos: 45917
Página Fernando Henrique Cardoso
Interagiram no período: 78711; likes: 96514; média: 1.23 likes por usuário
Confirmados nos eventos: 12779
Página Ciro Gomes
Interagiram no período: 18613; likes: 29074; média: 1.56 likes por usuário
Confirmados nos eventos: 64
Página Paulo Skaf
Interagiram no período: 15748; likes: 29769; média: 1.89 likes por usuário
Confirmados nos eventos: 2507
