### ISSUE TITLE
Formadores de opinião

### ISSUE THREAD

**Issue by marciomr** [marciomr/13M#58]
Rodando na máquina de Lo.

**Comment by andrechalom** [comment]
Alguns ficaram comigo:

Página Marco Antonio Villa
Interagiram no período: 64369; likes: 475739; média: 7.39 likes por usuário
Confirmados nos eventos: 13991

Página Lobão, o legítimo
Interagiram no período: 21614; likes: 38466; média: 1.78 likes por usuário
Confirmados nos eventos: 3711

**Comment by andrechalom** [comment]
Resultados de Lo:
Página Socialista Morena
Interagiram no período: 121141; likes: 546579; média: 4.51 likes por usuário
Confirmados nos eventos: 338
Página Danilo Gentili
Interagiram no período: 734265; likes: 1338092; média: 1.82 likes por usuário
Confirmados nos eventos: 14365
Página Rafinha Bastos
Interagiram no período: 392546; likes: 714912; média: 1.82 likes por usuário
Confirmados nos eventos: 4707
Página Marcelo Tas
Interagiram no período: 66642; likes: 85310; média: 1.28 likes por usuário
Confirmados nos eventos: 2448
Página Leonardo Sakamoto
Interagiram no período: 70775; likes: 137719; média: 1.95 likes por usuário
Confirmados nos eventos: 428
Página Eliane Brum
Interagiram no período: 9619; likes: 13606; média: 1.41 likes por usuário
Confirmados nos eventos: 84
Página Ricardo Boechat
Interagiram no período: 141759; likes: 271852; média: 1.92 likes por usuário
Confirmados nos eventos: 9394
Página Reinaldo Azevedo
Interagiram no período: 46022; likes: 263692; média: 5.73 likes por usuário
Confirmados nos eventos: 10845
Página Gregorio Duvivier
Interagiram no período: 37879; likes: 60376; média: 1.59 likes por usuário
Confirmados nos eventos: 128
Página Guilherme Boulos
Interagiram no período: 5809; likes: 9457; média: 1.63 likes por usuário
Confirmados nos eventos: 8
Página Kim Kataguiri
Interagiram no período: 82137; likes: 340267; média: 4.14 likes por usuário
Confirmados nos eventos: 11684
Página Raquel Sheherazade - Opinião
Interagiram no período: 0; likes: 0; média: NaN likes por usuário
Confirmados nos eventos: 0
Página Rodrigo Constantino
Interagiram no período: 6382; likes: 25960; média: 4.07 likes por usuário
Confirmados nos eventos: 1647
Página Olavo de Carvalho
Interagiram no período: 64815; likes: 903623; média: 13.94 likes por usuário
Confirmados nos eventos: 8409
Página José Luiz Datena
Interagiram no período: 0; likes: 0; média: NaN likes por usuário
Confirmados nos eventos: 0
Página Luiz Felipe Pondé
Interagiram no período: 3099; likes: 3768; média: 1.22 likes por usuário
Confirmados nos eventos: 472
Página Demétrio Magnoli
Interagiram no período: 710; likes: 1187; média: 1.67 likes por usuário
Confirmados nos eventos: 150

**Comment by andrechalom** [comment]
Página Tico Santa Cruz
Interagiram no período: 749019; likes: 2268967; média: 3.03 likes por usuário
Confirmados nos eventos: 3942
