### ISSUE TITLE
Movimentos

### ISSUE THREAD

**Issue by marciomr** [marciomr/13M#59]
Rodando na máquina de Chalom

**Comment by andrechalom** [comment]
Página Amigos da Rota
Interagiram no período: 251572; likes: 1433045; média: 5.7 likes por usuário
Confirmados nos eventos: 6045

Página Polícia Militar do Estado de São Paulo
Interagiram no período: 93520; likes: 337922; média: 3.61 likes por usuário
Confirmados nos eventos: 2856

Página Greenpeace Brasil
Interagiram no período: 162936; likes: 332744; média: 2.04 likes por usuário
Confirmados nos eventos: 4146

Página AnonymousBrasil
Interagiram no período: 19022; likes: 33259; média: 1.75 likes por usuário
Confirmados nos eventos: 1464

Página Fundação Lemann
Interagiram no período: 5001; likes: 6265; média: 1.25 likes por usuário
Confirmados nos eventos: 167

Página Infancia Livre de Consumismo
Interagiram no período: 35289; likes: 59636; média: 1.69 likes por usuário
Confirmados nos eventos: 614

Página Mamatraca
Interagiram no período: 28755; likes: 69882; média: 2.43 likes por usuário
Confirmados nos eventos: 399

Página Coletivo Desentorpecendo A Razão
Interagiram no período: 12495; likes: 14632; média: 1.17 likes por usuário
Confirmados nos eventos: 105

Página Travesti Reflexiva
Interagiram no período: 20758; likes: 31263; média: 1.51 likes por usuário
Confirmados nos eventos: 22

Página Não Me Kahlo
Interagiram no período: 250196; likes: 505304; média: 2.02 likes por usuário
Confirmados nos eventos: 1231

Página Todos Pela Educação - Página Oficial
Interagiram no período: 19075; likes: 36638; média: 1.92 likes por usuário
Confirmados nos eventos: 215

Página Vem Pra Rua Brasil
Interagiram no período: 616044; likes: 3166915; média: 5.14 likes por usuário
Confirmados nos eventos: 106837

Página Feminismo Sem Demagogia -  Original
Interagiram no período: 220031; likes: 483022; média: 2.2 likes por usuário
Confirmados nos eventos: 610

Página Vamos juntas?
Interagiram no período: 51091; likes: 221117; média: 4.33 likes por usuário
Confirmados nos eventos: 245

Página Movimento Contra Corrupção
Interagiram no período: 470298; likes: 3446111; média: 7.33 likes por usuário
Confirmados nos eventos: 36776

Página Movimento Queromedefender
Interagiram no período: 138435; likes: 310588; média: 2.24 likes por usuário
Confirmados nos eventos: 12666

Página Movimento Conviva
Interagiram no período: 52789; likes: 58049; média: 1.1 likes por usuário
Confirmados nos eventos: 652

Página Passe Livre São Paulo
Interagiram no período: 8486; likes: 14427; média: 1.7 likes por usuário
Confirmados nos eventos: 114

Página MST - Movimento dos Trabalhadores Sem Terra
Interagiram no período: 36030; likes: 105074; média: 2.92 likes por usuário
Confirmados nos eventos: 71

Página SP invisível
Interagiram no período: 20810; likes: 44595; média: 2.14 likes por usuário
Confirmados nos eventos: 177

Página Geledés Instituto da Mulher Negra
Interagiram no período: 125424; likes: 323983; média: 2.58 likes por usuário
Confirmados nos eventos: 509

Página Não fechem minha escola
Interagiram no período: 42820; likes: 99945; média: 2.33 likes por usuário
Confirmados nos eventos: 179

Página O Mal Educado
Interagiram no período: 7349; likes: 15265; média: 2.08 likes por usuário
Confirmados nos eventos: 11

Página Mtst Trabalhadores Sem Teto
Interagiram no período: 5536; likes: 11010; média: 1.99 likes por usuário
Confirmados nos eventos: 10

Página Revoltados ON LINE
Interagiram no período: 567113; likes: 3640495; média: 6.42 likes por usuário
Confirmados nos eventos: 49570

Página Movimento Brasil Livre
Interagiram no período: 612424; likes: 2619785; média: 4.28 likes por usuário
Confirmados nos eventos: 65720

**Comment by andrechalom** [comment]
OK, fiz o Anti-PT diretamente pelo banco de dados. Foi ridiculamente rápido. Estou pensando em só transferir o "results" para ser 100% feito pelo banco de dados. Also, estou postando aqui pq o "Partido" Anti-PT não é um partido ;)

Interagiram: 877755. Likes: 6541676. Isso dá 7.45 likes / usuário. 
Confirmados nos eventos: 59524

**Comment by marciomr** [comment]
No branch novo fiz alterações que deixaram o results bem mais rápido. Vou testar isso amanhã e se tudo estiver certo faço o merge.
