### ISSUE TITLE
Partidos

### ISSUE THREAD

**Issue by andrechalom** [marciomr/13M#61]

**Comment by marciomr** [comment]
Resultados 13M
Lendo banco de dados...
Página Democratas
Interagiram no período: 33400; likes: 79563; média: 2.38 likes por usuário
Confirmados nos eventos: 4509
Página Partido Novo
Interagiram no período: 65449; likes: 214060; média: 3.27 likes por usuário
Confirmados nos eventos: 11608
Página PMDB Nacional
Interagiram no período: 3154; likes: 12193; média: 3.87 likes por usuário
Confirmados nos eventos: 236
Página Partido dos Trabalhadores
Interagiram no período: 219059; likes: 1346031; média: 6.14 likes por usuário
Confirmados nos eventos: 685

**Comment by andrechalom** [comment]
Página Solidariedade
Interagiram no período: 2271; likes: 6238; média: 2.75 likes por usuário
Confirmados nos eventos: 160
Página REDE
Interagiram no período: 10921; likes: 32928; média: 3.02 likes por usuário
Confirmados nos eventos: 592

**Comment by andrechalom** [comment]
Página Partido Novo
Interagiram no período: 65670; likes: 214070; média: 3.26 likes por usuário
Confirmados nos eventos: 11605

Página PSOL 50 - Partido Socialismo e Liberdade
Interagiram no período: 30174; likes: 70108; média: 2.32 likes por usuário
Confirmados nos eventos: 110

Página PSDB
Interagiram no período: 381395; likes: 1337459; média: 3.51 likes por usuário
Confirmados nos eventos: 35760

EDIT: o Partido anti-PT foi transferido para o Movimentos. Partidos encerrados.

**Comment by andrechalom** [comment]
É, o Anti-PT está demorando infiniiito pq ele tem 6 milhões de likes; o dobro do segundo colocado até agora (Revoltados Online)
